
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.trash-core]
audit-as-crates-io = false

[policy.trash-forensic]
audit-as-crates-io = false

[[exemptions.autocfg]]
version = "1.5.1"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.45"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.118"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.trash-core]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.trash-forensic]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"
